version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: training_vue_node
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    command: sh -c "cd training_vue && yarn serve"
    ports:
      - "8080:8080"
