version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    command: sh -c "if [ -d ./training_vue/node_modules ]; then cd training_vue && npm run serve; fi"
    ports:
      - "8080:8080"
